import { eventConfig } from "../app/eventConfig";
function SectionHeading({ eyebrow, title }: { eyebrow: string; title: string }) {
  return <div style={{ textAlign: "center", marginBottom: 34 }}><p className="kicker">{eyebrow}</p><h2 className="display" style={{ fontSize: "var(--text-h2)", margin: "8px 0 0", textTransform: "uppercase", letterSpacing: "0.06em" }}>{title}</h2></div>;
}

export function OpeningQuote() {
  return <section className="section-pad" style={{ background: "var(--color-ink)", color: "white", textAlign: "center" }}><div className="container"><p style={{ fontFamily: "var(--font-script)", fontSize: "clamp(2rem, 5vw, 3.5rem)", margin: 0 }}>“</p><blockquote style={{ maxWidth: "700px", margin: "-10px auto 18px", fontFamily: "var(--font-body)", fontSize: "clamp(1.2rem, 2.5vw, 1.65rem)", lineHeight: 1.65, fontStyle: "italic" }}>{eventConfig.quote.text}</blockquote><cite style={{ fontFamily: "var(--font-ui)", fontSize: 11, letterSpacing: "0.2em", textTransform: "uppercase", fontStyle: "normal", opacity: 0.7 }}>{eventConfig.quote.source}</cite><p style={{ margin: "28px auto 0", maxWidth: "45ch", fontFamily: "var(--font-body)", fontSize: 16, opacity: 0.82 }}>Dengan penuh sukacita, kami menyambut Anda di halaman kisah cinta kami.</p></div></section>;
}

export function CoupleProfile() {
  const person = (data: typeof eventConfig.groom) => <div className="stagger" style={{ textAlign: "center" }}><figure className="img-hover" style={{ margin: "0 auto 20px", width: "min(100%, 260px)", aspectRatio: "3 / 4", overflow: "hidden", borderRadius: 160, border: "1px solid var(--color-line)" }}><img src={data.image} alt={`Portrait ${data.fullName}`} style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "50% 20%" }} /></figure><p className="kicker">{data.nickname}</p><h3 className="display" style={{ fontSize: 30, margin: "8px 0", textTransform: "uppercase" }}>{data.fullName}</h3><p style={{ maxWidth: 28 + "ch", margin: "0 auto", color: "var(--color-muted)", fontFamily: "var(--font-body)", fontStyle: "italic", fontSize: 15 }}>{data.parents}</p></div>;
  return <section className="section-pad" style={{ background: "var(--color-paper-alt)" }}><div className="container"><SectionHeading eyebrow="The Couple" title="Groom & Bride" /><div style={{ display: "grid", gridTemplateColumns: "1fr auto 1fr", gap: 24, alignItems: "center" }}>{person(eventConfig.groom)}<span className="script" style={{ fontSize: 54, color: "var(--color-accent)" }}>&</span>{person(eventConfig.bride)}</div></div><style>{`@media(max-width:767px){section div[style*="grid-template-columns: 1fr auto 1fr"]{grid-template-columns:1fr!important}.script{margin:0 auto}}`}</style></section>;
}

export function LoveStory() {
  return <section className="section-pad" style={{ background: "var(--color-paper)" }}><div className="container"><SectionHeading eyebrow="Our Journey" title="Love Story" /><div style={{ maxWidth: 760, margin: "0 auto", display: "grid", gap: 28 }}>{eventConfig.loveStory.map((item, index) => <article key={item.year} style={{ display: "grid", gridTemplateColumns: "80px 1fr", gap: 20, alignItems: "start" }}><div style={{ fontFamily: "var(--font-display)", fontSize: 26, color: "var(--color-accent-deep)", borderRight: "1px solid var(--color-line)", minHeight: 90 }}>{item.year}</div><div style={{ display: "grid", gridTemplateColumns: item.image ? "1fr 120px" : "1fr", gap: 16 }}>{<div><h3 className="display" style={{ fontSize: 25, margin: 0, textTransform: "uppercase" }}>{item.title}</h3><p style={{ margin: "8px 0 0", fontFamily: "var(--font-body)", color: "var(--color-muted)", fontSize: 15 }}>{item.description}</p></div>}{item.image && <img src={item.image} alt="" style={{ width: 120, height: 90, objectFit: "cover", borderRadius: 4 }} />}</div></article>)}</div></div></section>;
}

export function WeddingGift() {
  return <section className="section-pad" style={{ background: "var(--color-ink)", color: "white", textAlign: "center" }}><div className="container"><SectionHeading eyebrow="A Token of Love" title="Wedding Gift" /><p style={{ maxWidth: "48ch", margin: "0 auto 28px", opacity: 0.78, fontFamily: "var(--font-body)", fontSize: 16 }}>Doa dan kehadiran Anda adalah hadiah terindah. Jika berkenan memberikan tanda kasih, dapat melalui:</p><div style={{ maxWidth: 420, margin: "0 auto", padding: 28, border: "1px solid rgba(255,255,255,.25)", background: "rgba(255,255,255,.06)" }}><p className="kicker" style={{ color: "rgba(255,255,255,.7)" }}>{eventConfig.gift.bankName}</p><p style={{ margin: "10px 0", fontFamily: "var(--font-display)", fontSize: 30, letterSpacing: ".08em" }}>{eventConfig.gift.accountNumber}</p><p style={{ margin: 0, fontFamily: "var(--font-ui)", fontSize: 11, letterSpacing: ".12em", textTransform: "uppercase", opacity: .75 }}>a.n. {eventConfig.gift.accountName}</p></div></div></section>;
}

export function GuestQr() {
  const guest = new URLSearchParams(window.location.search).get("guest") || "guest";
  if (!eventConfig.guestQrEnabled) return null;
  const qrUrl = `https://quickchart.io/qr?text=${encodeURIComponent(`${window.location.origin}${window.location.pathname}?guest=${guest}`)}&size=220`;
  return <section className="section-pad" style={{ background: "var(--color-paper-alt)", textAlign: "center" }}><div className="container"><SectionHeading eyebrow="For Your Arrival" title="Guest Check-in" /><p style={{ color: "var(--color-muted)", fontFamily: "var(--font-body)" }}>Tunjukkan kode personal ini kepada penerima tamu saat tiba di venue.</p><img src={qrUrl} alt={`QR check-in untuk ${guest}`} width="180" height="180" style={{ margin: "24px auto 14px", background: "white", padding: 10 }} /><p className="kicker">Guest: {guest}</p></div></section>;
}

export function Closing() {
  return <footer className="section-pad" style={{ background: "var(--color-ink)", color: "white", textAlign: "center" }}><div className="container"><p className="script" style={{ fontSize: 34, margin: 0 }}>Thank you</p><p className="display" style={{ fontSize: 34, margin: "10px 0", textTransform: "uppercase", letterSpacing: ".08em" }}>{eventConfig.coupleNames}</p><p style={{ maxWidth: "42ch", margin: "0 auto", opacity: .72, fontFamily: "var(--font-body)", fontSize: 16 }}>Terima kasih atas doa, cinta, dan kehadiran Anda dalam hari bahagia kami.</p><div style={{ width: 40, height: 1, background: "rgba(255,255,255,.35)", margin: "28px auto" }} /><p style={{ margin: 0, fontFamily: "var(--font-ui)", fontSize: 10, letterSpacing: ".16em", textTransform: "uppercase", opacity: .45 }}>A wedding story by Invitato</p></div></footer>;
}
